services:
  paymybuddy-db:
    image: jidel1/projet-jidel-paymybuddy-db
    container_name: paymybuddy-db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  paymybuddy-backend:
    image: jidel1/projet-jidel-paymybuddy-backend
    depends_on:
      - paymybuddy-db
    container_name: paymybuddy-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://paymybuddy-db:3306/db_paymybuddy
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    expose:
      - 8080
volumes:
  db_data: